"""Add agent execution tracing

Revision ID: 28b74fcd8361
Revises: cecaba4ebe95
Create Date: 2026-08-23 03:34:45.655538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28b74fcd8361'
down_revision: Union[str, Sequence[str], None] = 'cecaba4ebe95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_execution',
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_history.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('ix_agent_execution_chat_id_created_at', 'agent_execution', ['chat_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_execution_execution_id'), 'agent_execution', ['execution_id'], unique=False)
    op.create_index('ix_agent_execution_org_created_at', 'agent_execution', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_execution_request_id'), 'agent_execution', ['request_id'], unique=False)
    op.create_index(op.f('ix_chat_source_source_id'), 'chat_source', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_source_source_id'), table_name='chat_source')
    op.alter_column('chat_history', 'feedback',
               existing_type=postgresql.ENUM('Good', 'Satisfactory', 'Bad', name='feedbacktype'),
               nullable=True)
    op.drop_index(op.f('ix_agent_execution_request_id'), table_name='agent_execution')
    op.drop_index('ix_agent_execution_org_created_at', table_name='agent_execution')
    op.drop_index(op.f('ix_agent_execution_execution_id'), table_name='agent_execution')
    op.drop_index('ix_agent_execution_chat_id_created_at', table_name='agent_execution')
    op.drop_table('agent_execution')
    # ### end Alembic commands ###
