"""Added Unique constarints

Revision ID: 3ff808caaa97
Revises: c59209c0fab6
Create Date: 2026-07-10 09:44:57.809512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff808caaa97'
down_revision: Union[str, Sequence[str], None] = 'c59209c0fab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_department_org_name', 'departments', ['organization_id', 'name'])
    op.create_unique_constraint('uq_team_department_name', 'teams', ['department_id', 'name'])
    op.alter_column('users', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_team_department_name', 'teams', type_='unique')
    op.drop_constraint('uq_department_org_name', 'departments', type_='unique')
    # ### end Alembic commands ###
