"""add document chunks

Revision ID: 6c7f9f112004
Revises: dac70d7422bd
Create Date: 2026-07-29 17:31:39.624731

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7f9f112004'
down_revision: Union[str, Sequence[str], None] = 'dac70d7422bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

embedding_status_enum = postgresql.ENUM(
    "PENDING",
    "PROCESSING",
    "COMPLETED",
    "FAILED",
    name="embeddingstatus",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    embedding_status_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk_index'),
    sa.UniqueConstraint('vector_id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_id'), 'document_chunks', ['chunk_id'], unique=False)
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('embedding_status', embedding_status_enum, nullable=False,server_default='PENDING'),)
    op.alter_column("documents","embedding_status",server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding_status')
    op.drop_column('documents', 'embedding_model')
    op.drop_index(op.f('ix_document_chunks_chunk_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    embedding_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
