"""Made principal id col in DocumentACL table nullable

Revision ID: dac70d7422bd
Revises: dcd48ef2006c
Create Date: 2026-07-26 09:29:09.993188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac70d7422bd'
down_revision: Union[str, Sequence[str], None] = 'dcd48ef2006c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_acls', 'principal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_acls', 'principal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
