"""Modified document model

Revision ID: ecce575d4b37
Revises: 867e8fc77a01
Create Date: 2026-07-24 15:07:37.043807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecce575d4b37'
down_revision: Union[str, Sequence[str], None] = '867e8fc77a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('documents', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('documents', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'uploaded_at')
    # ### end Alembic commands ###
