"""add embedding to document chunks

Revision ID: f2cf0054f8fa
Revises: fcd82b2f1a9e
Create Date: 2026-08-16 22:28:01.511874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'f2cf0054f8fa'
down_revision: Union[str, Sequence[str], None] = 'fcd82b2f1a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks',sa.Column('embedding', Vector(1024), nullable=True))   
    op.drop_constraint(op.f('document_chunks_vector_id_key'), 'document_chunks', type_='unique')
    op.drop_column('document_chunks', 'vector_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('vector_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('document_chunks_vector_id_key'), 'document_chunks', ['vector_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
