from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from langchain.tools import ToolRuntime, tool
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.enums.enums import UserRole
from app.models.department import Department
from app.models.organization import Organization
from app.models.team import Team
from app.models.users import User

# Runtime Context

@dataclass
class DataAgentContext:
    """
    Runtime-only dependencies for the Enterprise Data Agent.

    These values are supplied by the application and are NEVER
    generated by the LLM as tool arguments.
    """

    db: Session
    current_user: User

# Internal Helpers

def _serialize_user(user: User,*,department: Department | None = None,team: Team | None = None) -> dict[str, Any]:
    """
    Convert a User ORM object into safe tool output.
    SUPER_ADMIN users should already have been excluded
    before this function is called.
    """

    return {
        "user_id": user.user_id,
        "name": user.name,
        "email": user.email,
        "role": (
            user.role.value
            if hasattr(user.role, "value")
            else str(user.role)
        ),
        "organization_id": user.organization_id,
        "department": (
            {
                "department_id": department.department_id,
                "name": department.name,
            }
            if department is not None
            else None
        ),
        "team": (
            {
                "team_id": team.team_id,
                "name": team.name,
            }
            if team is not None
            else None
        ),
    }

def _base_user_conditions(*,current_user: User) -> list[Any]:
    """
    Security boundary for every user-search operation.
    Users can only discover users from their own organization.
    SUPER_ADMIN users are never exposed through Agent 3.
    """

    return [
        User.organization_id== current_user.organization_id,
        User.role != UserRole.SUPER_ADMIN
    ]

def _get_user_with_relationships(*,db: Session,user: User) -> dict[str, Any]:
    """
    Fetch department/team information for a user.
    Both relationships are additionally constrained to the
    user's organization.
    """

    department: Department | None = None
    team: Team | None = None

    if user.department_id is not None:
        department = db.execute(
            select(Department).where(
                Department.department_id== user.department_id,
                Department.organization_id== user.organization_id,
            )
        ).scalar_one_or_none()

    if user.team_id is not None:
        team = db.execute(
            select(Team).where(
                Team.team_id == user.team_id,
                Team.organization_id== user.organization_id,
            )
        ).scalar_one_or_none()

    return _serialize_user(
        user,
        department=department,
        team=team,
    )

# 1. CURRENT USER
@tool
def get_current_user(*,runtime: ToolRuntime[DataAgentContext]) -> dict[str, Any]:
    """
    Get information about the currently authenticated user.
    Use this for questions such as:
    The authenticated user is supplied by the application runtime.
    """

    db = runtime.context.db
    current_user = runtime.context.current_user

    return _get_user_with_relationships(
        db=db,
        user=current_user,
    )

# 2. SEARCH USERS
@tool
def search_users(
    user_id: int | None = None,
    email: str | None = None,
    name: str | None = None,
    department_id: int | None = None,
    team_id: int | None = None,
    limit: int = 10,
    *,
    runtime: ToolRuntime[DataAgentContext]
) -> dict[str, Any]:
    """
    Search users within the authenticated user's organization.

    Available filters:
    - user_id
    - email
    - name
    - department_id
    - team_id

    Multiple filters may be combined.

    Name searches may return multiple users. Never arbitrarily
    choose one if several users match.
    """

    if limit <= 0:
        raise ValueError("limit must be greater than zero.")

    limit = min(limit, 20)

    db = runtime.context.db
    current_user = runtime.context.current_user

    conditions = _base_user_conditions(current_user=current_user,)

    if user_id is not None:
        conditions.append(User.user_id == user_id)

    if email is not None:
        normalized_email = email.strip()

        if normalized_email:
            conditions.append(User.email == normalized_email)

    if name is not None:
        normalized_name = name.strip()

        if normalized_name:
            conditions.append(
                User.name.ilike(
                    f"%{normalized_name}%"
                )
            )

    if department_id is not None:
        conditions.append(User.department_id == department_id)

    if team_id is not None:
        conditions.append(User.team_id == team_id)

    stmt = (
        select(User)
        .where(*conditions)
        .order_by(
            User.name.asc(),
            User.user_id.asc(),
        )
        .limit(limit)
    )

    users = (db.execute(stmt).scalars().all())

    results = [
        _get_user_with_relationships(
            db=db,
            user=user,
        )
        for user in users
    ]

    return {
        "found": bool(results),
        "match_count": len(results),
        "users": results,
    }

# 3. GET DEPARTMENT
@tool
def get_department(department_id: int,*,runtime: ToolRuntime[DataAgentContext]) -> dict[str, Any] | None:
    """
    Get a department by ID.
    The department must belong to the authenticated user's
    organization.
    """

    db = runtime.context.db
    current_user = runtime.context.current_user

    department = db.execute(
        select(Department).where(
            Department.department_id == department_id,
            Department.organization_id == current_user.organization_id,
        )
    ).scalar_one_or_none()

    if department is None:
        return None

    return {
        "department_id": department.department_id,
        "name": department.name,
        "description": department.description,
        "organization_id": department.organization_id,
    }

# 4. SEARCH DEPARTMENTS
@tool
def search_departments(name: str | None = None,limit: int = 10,*,runtime: ToolRuntime[DataAgentContext]) -> dict[str, Any]:
    """
    Search departments by name within the authenticated user's
    organization.
    Multiple departments with similar names may be returned.
    """

    if limit <= 0:
        raise ValueError("limit must be greater than zero.")

    limit = min(limit, 20)

    db = runtime.context.db
    current_user = runtime.context.current_user

    conditions = [Department.organization_id == current_user.organization_id ]

    if name is not None:
        normalized_name = name.strip()

        if normalized_name:
            conditions.append(
                Department.name.ilike(
                    f"%{normalized_name}%"
                )
            )

    stmt = (
        select(Department)
        .where(*conditions)
        .order_by(
            Department.name.asc(),
            Department.department_id.asc(),
        )
        .limit(limit)
    )

    departments = (db.execute(stmt).scalars().all())

    return {
        "found": bool(departments),
        "match_count": len(departments),
        "departments": [
            {
                "department_id": department.department_id,
                "name": department.name,
                "organization_id": department.organization_id,
            }
            for department in departments
        ],
    }

# 5. LIST USERS IN DEPARTMENT
@tool
def list_department_users(department_id: int,limit: int = 50,*,runtime: ToolRuntime[DataAgentContext],) -> dict[str, Any]:
    """
    List users belonging to a department.
    The department must belong to the authenticated user's
    organization.
    """

    if limit <= 0:
        raise ValueError(
            "limit must be greater than zero."
        )

    limit = min(limit, 100)

    db = runtime.context.db
    current_user = runtime.context.current_user

    department = db.execute(
        select(Department).where(
            Department.department_id== department_id,
            Department.organization_id== current_user.organization_id
        )
    ).scalar_one_or_none()

    if department is None:
        return {
            "found": False,
            "department": None,
            "match_count": 0,
            "users": [],
        }

    stmt = (
        select(User)
        .where(
            User.organization_id== current_user.organization_id,
            User.department_id == department_id,
            User.role != UserRole.SUPER_ADMIN,
        )
        .order_by(
            User.name.asc(),
            User.user_id.asc(),
        )
        .limit(limit)
    )

    users = (db.execute(stmt).scalars().all())

    return {
        "found": True,
        "department": {
            "department_id": department.department_id,
            "name": department.name,
        },
        "match_count": len(users),
        "users": [
            _get_user_with_relationships(
                db=db,
                user=user,
            )
            for user in users
        ],
    }

# 6. GET TEAM
@tool
def get_team(team_id: int,*,runtime: ToolRuntime[DataAgentContext]) -> dict[str, Any] | None:
    """
    Get a team by ID.
    The team must belong to the authenticated user's
    organization.
    """

    db = runtime.context.db
    current_user = runtime.context.current_user

    team = db.execute(
        select(Team).where(
            Team.team_id == team_id,
            Team.organization_id == current_user.organization_id,
        )
    ).scalar_one_or_none()

    if team is None:
        return None

    return {
        "team_id": team.team_id,
        "name": team.name,
        "description": team.description,
        "department_id": team.department_id,
        "organization_id": team.organization_id,
    }

# 7. SEARCH TEAMS
@tool
def search_teams(name: str | None = None,limit: int = 10,*,runtime: ToolRuntime[DataAgentContext]) -> dict[str, Any]:
    """
    Search teams by name within the authenticated user's
    organization.
    Multiple teams with similar names may be returned.
    """

    if limit <= 0:
        raise ValueError(
            "limit must be greater than zero."
        )

    limit = min(limit, 20)

    db = runtime.context.db
    current_user = runtime.context.current_user

    conditions = [
        Team.organization_id == current_user.organization_id
    ]

    if name is not None:
        normalized_name = name.strip()

        if normalized_name:
            conditions.append(
                Team.name.ilike(
                    f"%{normalized_name}%"
                )
            )

    stmt = (
        select(Team)
        .where(*conditions)
        .order_by(
            Team.name.asc(),
            Team.team_id.asc(),
        )
        .limit(limit)
    )

    teams = (db.execute(stmt).scalars().all())

    return {
        "found": bool(teams),
        "match_count": len(teams),
        "teams": [
            {
                "team_id": team.team_id,
                "name": team.name,
                "organization_id": team.organization_id,
                "department_id": team.department_id,
            }
            for team in teams
        ],
    }

# 8. LIST USERS IN TEAM
@tool
def list_team_users(team_id: int,limit: int = 50,*,runtime: ToolRuntime[DataAgentContext]) -> dict[str, Any]:
    """
    List users belonging to a team.
    The team must belong to the authenticated user's
    organization.
    """

    if limit <= 0:
        raise ValueError("limit must be greater than zero.")

    limit = min(limit, 100)

    db = runtime.context.db
    current_user = runtime.context.current_user

    team = db.execute(
        select(Team).where(
            Team.team_id == team_id,
            Team.organization_id == current_user.organization_id,
        )
    ).scalar_one_or_none()

    if team is None:
        return {
            "found": False,
            "team": None,
            "match_count": 0,
            "users": [],
        }

    stmt = (
        select(User)
        .where(
            User.organization_id == current_user.organization_id,
            User.team_id == team_id,
            User.role != UserRole.SUPER_ADMIN,
        )
        .order_by(
            User.name.asc(),
            User.user_id.asc(),
        )
        .limit(limit)
    )

    users = (db.execute(stmt).scalars().all())

    return {
        "found": True,
        "team": {
            "team_id": team.team_id,
            "name": team.name,
            "department_id": team.department_id,
        },
        "match_count": len(users),
        "users": [
            _get_user_with_relationships(
                db=db,
                user=user,
            )
            for user in users
        ],
    }

# 9. GET ORGANIZATION
@tool
def get_organization( *, runtime: ToolRuntime[DataAgentContext]) -> dict[str, Any] | None:
    """
    Get the authenticated user's organization.
    """

    db = runtime.context.db
    current_user = runtime.context.current_user

    organization = db.execute(
        select(Organization).where(
            Organization.organization_id == current_user.organization_id,
        )
    ).scalar_one_or_none()

    if organization is None:
        return None

    return {
        "organization_id": organization.organization_id,
        "name": organization.name,
        "industry": organization.industry,
    }

# Tool Collection
DATA_AGENT_TOOLS = [
    get_current_user,
    search_users,
    get_department,
    search_departments,
    list_department_users,
    get_team,
    search_teams,
    list_team_users,
    get_organization,
]